export const {
  VITE_API_GET: API_GET,
  VITE_API_POST: API_POST,
  VITE_CLOUD_NAME: CLOUD_NAME,
  VITE_CLOUD_API_KEY: CLOUD_API_KEY,
  VITE_CLOUD_UPLOAD_PRESET: CLOUD_UPLOAD_PRESET,
  VITE_CLOUD_TAGS: CLOUD_TAGS
} = import.meta.env
